# basic image
FROM node:16-alpine

# do some change
WORKDIR '/app'
COPY package.json .
RUN npm install

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

# start command
CMD [ "npm", "run", "start"]